FROM node

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

# Install nodemon globally
RUN npm install -g nodemon

COPY . .

CMD npm config set prefer-offline true && nodemon --legacy-watch app.js
# legacy version that doesn't work anymore
# CMD npm config set cache-min 9999999 && npm run dev
